

name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Show current directory
      run: pwd

    - name: List current directory contents
      run: ls -lh


    - name: Copy WAR directly to EC2 (flatten path)
      run: |
        echo "${TEST_EC2_PVT_KEY}" > ec2_key.pem
        chmod 600 ec2_key.pem
        scp -i ec2_key.pem -o StrictHostKeyChecking=no webapp/target/*.war ubuntu@${TEST_EC2_HOST}:/home/ubuntu/test/
      env:
        TEST_EC2_HOST: ${{ secrets.TEST_EC2_HOST }}
        TEST_EC2_PVT_KEY: ${{ secrets.TEST_EC2_PVT_KEY }}
