

name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package
    
    - name: Copy WAR and Build Docker on EC2
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

        # Copy WAR file to EC2
        sshpass -p "${{ secrets.TEST_EC2_PASSWORD }}" scp -o StrictHostKeyChecking=no webapp/target/*.war ${{ secrets.TEST_EC2_USER }}@${{ secrets.TEST_EC2_HOST }}:/home/test/

        # SSH into EC2 and run Docker commands
        sshpass -p "${{ secrets.TEST_EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.TEST_EC2_USER }}@${{ secrets.TEST_EC2_HOST }} << 'EOF'
        cd /home/test
        docker stop webapp-container || true
        docker rm webapp-container || true
        docker build -t webapp-image .
        docker run -d -p 8080:8080 --name webapp-container webapp-image
        EOF
